[package]
name = "swc-plugin-minify-catch-param"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "SWC plugin that removes unused simple catch clause parameters"
authors = ["Alexander Zaytsev <zaytsev126@gmail.com>"]

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"

[dependencies]
swc_core = { version = "^80.0.0", features = [
  "ecma_ast",
  "ecma_plugin_transform",
] }

[dev-dependencies]
testing = "27.0.0"
swc_core = { version = "^80.0.0", features = [
  "ecma_parser",
  "testing_transform",
] }
